name: miws23

channels:
  - anaconda
  - pytorch
  - defaults

dependencies:
  - python=3.9
  - Cython==3.0.0
  - matplotlib==3.7.2
  - numpy==1.26.0
  - pytorch==2.1.0
  - scipy==1.11.1
  - tqdm==4.65.0
  - pip==23.2.1
  - scikit-learn==1.2.2
  - jupyter==1.0.0
  - ipython==8.15.0
  - pandas==2.0.3


  - pip:
    - mido==1.3.0
    - python-rtmidi==1.5.6
    - partitura==1.4.0
    - SoundFile==0.12.1
    - fastdtw==0.3.4
    - python-hiddenmarkov==0.1.3
    - appdirs==1.4.4
    - ipympl==0.9.3